version: 0.2

phases:

  install:
    commands:
      - echo Install started on `date`
      - apt-get update
      - apt-get install zip

  build:
    commands:
      - echo Build started on `date`
      - ./buildLambda.sh

  post_build:
    commands:
      - |
        if expr "${CODEBUILD_BUILD_ARN}" : ".*build/plv2qual:" >/dev/null; then
          BRANCHE="-qual";
        fi
      - |
        if expr "${CODEBUILD_BUILD_ARN}" : ".*build/plv2prod:" >/dev/null; then
          BRANCHE="-prod";
        fi
      - |
        if expr "${CODEBUILD_SOURCE_VERSION}" : "qual" >/dev/null; then
          BRANCHE="-qual";
        fi
      - |
        if expr "${CODEBUILD_SOURCE_VERSION}" : "prod" >/dev/null; then
          BRANCHE="-prod";
        fi
      - echo $BRANCHE
      - aws lambda update-function-code --function-name "pdf-splitter$BRANCHE" --zip-file fileb://lambda.zip
