version: 0.2

phases:

  install:
    commands:
      - echo Install started on `date`
      - apt-get update
      - apt-get install zip
    runtime-versions:
      python: 3.8

  build:
    commands:
      - echo Build started on `date`
      - ./buildLambda.sh

  post_build:
    commands:
      - aws lambda update-function-code --function-name "multi-lambda-pdfspliter-$BRANCHE" --zip-file fileb://lambda.zip
      - while [ "$statefunction" != "Successful" ]; do statefunction=$(aws lambda get-function --function-name "$PROJET-lambda-$NAME-$BRANCHE" | jq -r '.Configuration.LastUpdateStatus'); echo $statefunction; sleep 5; done
      - aws lambda publish-version --function-name "$PROJET-lambda-$NAME-$BRANCHE"
