version: 0.2

phases:

  install:
    commands:
      - echo Install started on `date`
      - apt-get update
      - apt-get install zip
    runtime-versions:
      python: 3.8

  build:
    commands:
      - echo Build started on `date`
      - ./buildLambda.sh

  post_build:
    commands:
      - aws lambda update-function-code --function-name "$PROJET-lambda-$NAME-$BRANCHE" --zip-file fileb://lambda.zip
